/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PerfectPDFExportPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  exportPreset: "professional",
  fontSize: 10,
  pageOrientation: "portrait",
  margins: "normal",
  preventTableSplits: true,
  preventCalloutSplits: true,
  preventListSplits: false,
  // Allow lists to break if needed
  optimizeTableWidth: true,
  wordWrap: true
};
var PRESETS = {
  teaching: {
    fontSize: 11,
    margins: "normal",
    preventTableSplits: true,
    preventCalloutSplits: true,
    preventListSplits: false,
    optimizeTableWidth: true,
    wordWrap: true
  },
  professional: {
    fontSize: 10,
    margins: "normal",
    preventTableSplits: true,
    preventCalloutSplits: true,
    preventListSplits: false,
    optimizeTableWidth: true,
    wordWrap: true
  },
  minimal: {
    fontSize: 9,
    margins: "narrow",
    preventTableSplits: true,
    preventCalloutSplits: false,
    preventListSplits: false,
    optimizeTableWidth: true,
    wordWrap: true
  }
};
var PerfectPDFExportPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    // Constants for timing
    this.STYLE_APPLY_DELAY = 100;
    // ms to wait for styles to apply
    this.CLEANUP_DELAY = 1e3;
  }
  // ms to wait before removing styles
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("file-down", "Export to Perfect PDF", async (evt) => {
      await this.exportCurrentFileToPDF();
    });
    this.addCommand({
      id: "export-to-perfect-pdf",
      name: "Export current note to Perfect PDF",
      callback: async () => {
        await this.exportCurrentFileToPDF();
      }
    });
    this.addCommand({
      id: "export-folder-to-pdf",
      name: "Export current folder to PDFs",
      callback: async () => {
        new import_obsidian.Notice("Batch export coming in v0.2.0!");
      }
    });
    this.addSettingTab(new PerfectPDFSettingTab(this.app, this));
    console.log("Perfect PDF Export plugin loaded");
  }
  onunload() {
    console.log("Perfect PDF Export plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Apply a preset to settings
   */
  applyPreset(preset) {
    const presetSettings = PRESETS[preset];
    Object.assign(this.settings, presetSettings);
    this.settings.exportPreset = preset;
  }
  /**
   * Main export function
   */
  async exportCurrentFileToPDF() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian.Notice("No active file to export");
      return;
    }
    new import_obsidian.Notice("Preparing PDF export...");
    try {
      const content = await this.app.vault.read(activeFile);
      const css = this.generateOptimizedCSS();
      await this.printWithCustomCSS(content, css);
      new import_obsidian.Notice("Print dialog opened. Save as PDF to complete export.");
    } catch (error) {
      console.error("Export failed:", error);
      new import_obsidian.Notice("PDF export failed. See console for details.");
    }
  }
  /**
   * Generate optimized CSS based on settings
   */
  generateOptimizedCSS() {
    const {
      fontSize,
      margins,
      pageOrientation,
      preventTableSplits,
      preventCalloutSplits,
      preventListSplits,
      optimizeTableWidth,
      wordWrap
    } = this.settings;
    let css = `
		@media print {
			/* Base font size */
			body {
				font-size: ${fontSize}pt;
				line-height: 1.5;
			}

			/* Margins and orientation */
			@page {
				margin: ${margins === "narrow" ? "0.5in" : margins === "wide" ? "1in" : "0.75in"};
				${pageOrientation !== "auto" ? `size: ${pageOrientation};` : ""}
			}

			/* Prevent horizontal overflow */
			* {
				max-width: 100%;
				box-sizing: border-box;
			}

			/* Word wrapping */
			${wordWrap ? `
			p, li, td, th {
				word-wrap: break-word;
				overflow-wrap: break-word;
				hyphens: auto;
			}
			` : ""}

			/* Table optimization */
			${preventTableSplits ? `
			table {
				page-break-inside: avoid !important;
			}
			` : ""}

			${optimizeTableWidth ? `
			table {
				width: 100%;
				max-width: 100%;
				table-layout: auto;
				font-size: 0.85em;
			}

			th, td {
				padding: 6px 8px;
				word-wrap: break-word;
				word-break: break-word;
				max-width: 200px;
			}
			` : ""}

			/* Callout optimization */
			${preventCalloutSplits ? `
			.callout {
				page-break-inside: avoid !important;
				margin: 1em 0;
			}
			` : ""}

			/* List optimization */
			${preventListSplits ? `
			ul, ol {
				page-break-inside: avoid !important;
			}
			` : `
			ul, ol {
				page-break-inside: auto;
			}
			`}

			li {
				page-break-inside: avoid !important;
			}

			/* Code blocks */
			pre, code {
				page-break-inside: avoid !important;
				white-space: pre-wrap !important;
				word-wrap: break-word !important;
			}

			/* Headings */
			h1, h2, h3, h4, h5, h6 {
				page-break-after: avoid !important;
				page-break-inside: avoid !important;
			}

			/* Keep heading with content */
			h1 + p, h2 + p, h3 + p {
				page-break-before: avoid !important;
			}

			/* Blockquotes */
			blockquote {
				page-break-inside: avoid !important;
			}

			/* Links - break if needed */
			a {
				word-break: break-all;
				overflow-wrap: break-word;
			}

			/* Images */
			img {
				page-break-inside: avoid !important;
				max-width: 100%;
			}
		}
		`;
    return css;
  }
  /**
   * Print with custom CSS
   * Applies custom CSS and triggers the print dialog for the active view
   */
  async printWithCustomCSS(content, css) {
    const styleEl = document.createElement("style");
    styleEl.id = "perfect-pdf-export-styles";
    styleEl.textContent = css;
    document.head.appendChild(styleEl);
    await new Promise((resolve) => setTimeout(resolve, this.STYLE_APPLY_DELAY));
    window.print();
    const cleanup = () => {
      const el = document.getElementById("perfect-pdf-export-styles");
      if (el)
        el.remove();
    };
    setTimeout(cleanup, this.CLEANUP_DELAY);
  }
};
var PerfectPDFSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Perfect PDF Export Settings" });
    new import_obsidian.Setting(containerEl).setName("Export preset").setDesc("Quick presets for different use cases").addDropdown((dropdown) => dropdown.addOption("teaching", "Teaching (readable, optimized for lessons)").addOption("professional", "Professional (balanced, clean)").addOption("minimal", "Minimal (compact, more content)").setValue(this.plugin.settings.exportPreset).onChange(async (value) => {
      this.plugin.applyPreset(value);
      await this.plugin.saveSettings();
      this.display();
    }));
    containerEl.createEl("h3", { text: "Layout Options" });
    new import_obsidian.Setting(containerEl).setName("Font size").setDesc("Base font size in points (8-14)").addSlider((slider) => slider.setLimits(8, 14, 1).setValue(this.plugin.settings.fontSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.fontSize = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Page orientation").setDesc("Choose page orientation").addDropdown((dropdown) => dropdown.addOption("portrait", "Portrait").addOption("landscape", "Landscape").addOption("auto", "Auto (detect wide tables)").setValue(this.plugin.settings.pageOrientation).onChange(async (value) => {
      this.plugin.settings.pageOrientation = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Margins").setDesc("Page margins").addDropdown((dropdown) => dropdown.addOption("narrow", "Narrow (0.5in)").addOption("normal", "Normal (0.75in)").addOption("wide", "Wide (1in)").setValue(this.plugin.settings.margins).onChange(async (value) => {
      this.plugin.settings.margins = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Page Break Options" });
    new import_obsidian.Setting(containerEl).setName("Prevent table splits").setDesc("Keep tables on one page when possible").addToggle((toggle) => toggle.setValue(this.plugin.settings.preventTableSplits).onChange(async (value) => {
      this.plugin.settings.preventTableSplits = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Prevent callout splits").setDesc("Keep callouts on one page").addToggle((toggle) => toggle.setValue(this.plugin.settings.preventCalloutSplits).onChange(async (value) => {
      this.plugin.settings.preventCalloutSplits = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Prevent list splits").setDesc("Keep entire lists on one page (may cause overflow)").addToggle((toggle) => toggle.setValue(this.plugin.settings.preventListSplits).onChange(async (value) => {
      this.plugin.settings.preventListSplits = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Content Optimization" });
    new import_obsidian.Setting(containerEl).setName("Optimize table width").setDesc("Automatically adjust table columns to fit page").addToggle((toggle) => toggle.setValue(this.plugin.settings.optimizeTableWidth).onChange(async (value) => {
      this.plugin.settings.optimizeTableWidth = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable word wrap").setDesc("Break long words to prevent horizontal overflow").addToggle((toggle) => toggle.setValue(this.plugin.settings.wordWrap).onChange(async (value) => {
      this.plugin.settings.wordWrap = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("div", {
      cls: "setting-item-description",
      text: "\u{1F4A1} Tip: Use the ribbon icon or command palette to export the current note."
    });
  }
};
